language: r
r: devel
sudo: true
cache: packages
dist: trusty

warnings_are_errors: true

apt_packages:
  - qpdf

r_github_packages:
  - hadley/devtools
  - hadley/pkgdown

script:
  - R CMD build . ${R_BUILD_ARGS}
  - R CMD check `ls -1t *.tar.gz | head -n 1` ${R_CHECK_ARGS}$
  - R -e 'pkgdown::build_site()'
  - mv docs ..
  - rm -r *
  - mv ../docs/* .

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  on:
    branch: master
  target_branch: gh-pages
  
env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes --no-manual --compact-vignettes=gs+qpdf" 
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

cran: http://cran.rstudio.com
